services:
  php-fpm:
    build: { context: ., dockerfile: docker/php-fpm.Dockerfile }
    working_dir: /app
    environment:
      DB_DSN: "pgsql:host=postgres;port=5432;dbname=app"
      DB_USER: "app"
      DB_PASS: "app"
    volumes: [ ".:/app" ]
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    ports: [ "8080:80" ]
    volumes:
      - "./public:/app/public:ro"
      - "./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on: [ php-fpm ]

  worker:
    build: { context: ., dockerfile: docker/php-cli.Dockerfile }
    working_dir: /app
    command: ["php","worker.php"]
    environment:
      DB_DSN: "pgsql:host=postgres;port=5432;dbname=app"
      DB_USER: "app"
      DB_PASS: "app"
    volumes: [ ".:/app" ]
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
      image: postgres:16
      environment:
        POSTGRES_DB: app
        POSTGRES_USER: app
        POSTGRES_PASSWORD: app
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U app -d app"]
        interval: 2s
        timeout: 3s
        retries: 30
      volumes:
        - "pgdata:/var/lib/postgresql/data"
        - "./db/migrations:/docker-entrypoint-initdb.d:ro"

volumes:
  pgdata:
